pub mod accept;
mod auto_dot;
pub mod auto_dsl;
mod auto_fn_ast;
mod bootstrap;
pub use accept::{accept_proposal, AcceptProposalError, ProposalAcceptance, ProposalAcceptanceInput};
pub use auto_dot::{auto_accept_dot_proposal, AutoAcceptDotError};
pub use auto_dsl::{apply_dsl_proposal, AutoAcceptDslError};
pub use auto_fn_ast::{auto_accept_fn_ast, AutoAcceptFnAstError};
pub(crate) const DSL_PROOF_ID: &str = "proof.dsl.bootstrap";
pub(crate) const DSL_PREDICATE_ID: &str = "predicate.dsl.autoaccept";
pub(crate) const DSL_TICK_ID: &str = "tick.bootstrap";
